require: rubocop-performance

# Custom project config
AllCops:
  Exclude:
  - './Vagrantfile'
  - './vagrant-google.gemspec'

Layout/EmptyLinesAroundBlockBody:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Style/IfUnlessModifier:
  Enabled: false

Metrics/LineLength:
  Max: 120

Layout/HashAlignment:
  EnforcedHashRocketStyle: table

Style/HashSyntax:
  EnforcedStyle: no_mixed_keys
