name: Run unit tests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1

    - name: Set up Ruby 2.4
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.4.X

    - name: Unit tests
      run: |
        gem install bundler
        bundle install --jobs 4 --retry 3
        bundle exec rake

    - name: Linter
      uses: adwerx/pronto-ruby
      with:
        runners: >-
          rubocop
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}